[package]
edition = "2021"
name = "rust-prometheus-demo"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
actix-web-prom = "0.7.0"
env_logger = "0.10.0"
log = "0.4.20"
