global:
  scrape_interval: 5s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'app'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:3000'] # Metrics endpoint of the frontend application
        labels:
          group: 'app'
